[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$BEBIqdWacy6ltNa6lxKilA$UX2yP8ub6YOgDkBgi9E/ERXyl91OGrLe6MQrYThCoMxAOvLomga.Q7th0BBw2WaVVW2suNhkw9OQnMyDjuOK9w
db_host = db
db_user = odoo
db_password = odoo
db_port = 5432
workers = 0
max_cron_threads = 1
log_handler = [':INFO']
log_level = info
dev_mode = reload,qweb,sql,werkzeug
server_wide_modules = base,web,redis_session_store

