[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$5vyfEwIA4FzrXQsBwHjvfQ$OCDE1y3JsTXuEsobK//nNC/me3TgyLALkeTruQbLWRQuNlDZf8YyJQZ9ZTO1tLoB.N1fzksA53JlSu8CZe9jAQ
db_host = db
db_user = odoo
db_password = odoo
db_port = 5432
workers = 0
max_cron_threads = 1
log_handler = [':INFO']
log_level = info
dev_mode = reload,qweb,sql,werkzeug
server_wide_modules = base,web,redis_session_store

